### ISSUE TITLE
where is paper

### ISSUE THREAD

**Issue by shanpoyang654** [alessiochisari/federated-transfer-learning#1]
Thanks! But I cannot find this paper on the Internet.
Could you please send me a copy of your paper and explain how to run this code?

**Comment by alessiochisari** [comment]
Dear shanpoyang654,

Thank you for your interest in the project! I have update the README.md file, but in any case you have to upload the dataset provided on your Google Drive. After that, you have to load the .ipynb notebook on Google Colaboratory, and you will be able to run the cells. We have done several experiments, each notebook contains an experiment with related results. Regarding the paper, I'll leave you the link here: https://arxiv.org/abs/2206.13399.
Thank you.

Best regards,
AC


________________________________
Da: shanpoyang654 ***@***.***>
Inviato: mercoledì 8 marzo 2023 03:33
A: alessiochisari/federated-transfer-learning ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [alessiochisari/federated-transfer-learning] where is paper (Issue #1)


Thanks! But I cannot find this paper on the Internet.
Could you please send me a copy of your paper and explain how to run thiThanks! But I cannot find this paper on the Internet.
Could you please send me a copy of your paper and explain how to run this code?s code?
